alias reload!='. ~/.zshrc'
alias cls='clear' # Good 'ol Clear Screen command
alias l='ls -la'
alias b='cd "$OLDPWD"'
alias r='ranger'
alias grep='grep -in --color'
alias be='bundle exec'
alias h="history | grep -E -v '^ *[0-9]+ *h ' | grep "
alias pg='ping www.google.com'
