alias reload!='. ~/.zshrc'
alias clr='clear' # Good 'ol Clear Screen command
alias b='cd "$OLDPWD"'
alias r='ranger'
alias grep='grep -in --color'
alias be='bundle exec'
alias h="history | grep -E -v '^ *[0-9]+ *h ' | grep "
alias pg='ping www.google.com'
alias dotfiles='cd ~/.dotfiles'
alias gocode='cd ~/Code'
alias gogithub='cd ~/code/github'
alias edit='code'
# alias rm='trash'